#
# Trigger a review for the pull request using .github/workflows/review-pr.yml
#
name: Trigger PR review
on: pull_request
jobs:
  upload_pr_event:
    runs-on: ubuntu-latest
    steps:
      - name: Save event payload
        run: cp "$GITHUB_EVENT_PATH" event.json
      - name: Upload event payload
        uses: actions/upload-artifact@v4
        with:
          name: pr-event
          path: event.json
